Repository iTwin/iTwinUI-react, pull requests merged in 2021-05, with the labels that each got.

#46 Update to itwinui-css 0.12.0
  package.json
  src/core/Alert/Alert.tsx
  src/core/Buttons/DropdownButton/DropdownButton.test.tsx
  src/core/Buttons/DropdownButton/DropdownButton.tsx
  src/core/Buttons/IconButton/IconButton.tsx
  src/core/Buttons/IdeasButton/IdeasButton.tsx
  src/core/Buttons/SplitButton/SplitButton.test.tsx
  src/core/DatePicker/DatePicker.tsx
  src/core/ExpandableBlock/ExpandableBlock.tsx
  src/core/Modal/Modal.tsx
  src/core/ProgressIndicators/ProgressRadial/ProgressRadial.tsx
  src/core/RadioTiles/RadioTile.tsx
  src/core/Table/Table.tsx
  src/core/Tag/Tag.tsx
  src/core/Tile/Tile.tsx
  src/core/Toast/Toast.tsx
  src/core/UserIcon/UserIcon.test.tsx
  src/core/UserIcon/UserIcon.tsx
  src/core/utils/common.tsx
  stories/core/HorizontalTabs.stories.tsx
  stories/core/Tile.stories.tsx
  yarn.lock
Labels: maintenance

#47 Bump hosted-git-info
  package.json
  yarn.lock
Labels: maintenance

#55 Added audit-ci to suppress postcss vulnerability warnings
  .github/workflows/build.yml
  package.json
  yarn.lock
Labels: maintenance

#61 Improve overview story logic for hiding addons panel
  stories/intro/Overview.stories.tsx
Labels: maintenance

#92 Fix for Modal leaving overflow hidden on body
  src/core/Modal/Modal.test.tsx
  src/core/Modal/Modal.tsx
Labels: bug

#93 Update issue templates to include project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#71 New StylingProps added to ButtonGroup
  src/core/ButtonGroup/ButtonGroup.tsx
  src/core/utils/props.ts
Labels: bug

#94 Update to itwinui-css 0.17.1
  CHANGELOG.md
  package.json
  src/core/ProgressIndicators/ProgressRadial/ProgressRadial.test.tsx
  src/core/ProgressIndicators/ProgressRadial/ProgressRadial.tsx
  src/core/Wizard/Step.test.tsx
  src/core/Wizard/Step.tsx
  yarn.lock
Labels: dependencies
